[package]
name = "iquiji0-null-counter"
version = "0.1.0"
authors = ["Kosta Welke <kw@trinatives.com>"]
edition = "2018"

[dependencies]
"hyper" = "0.12"
"futures" = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"